# Generated by Django 2.1.3 on 2019-03-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.ImageField(upload_to='images/')),
                ('main', models.CharField(max_length=20)),
            ],
        ),
    ]
