# Generated by Django 2.1.3 on 2019-03-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_auto_20190312_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='root',
            field=models.CharField(default='', max_length=20),
        ),
    ]
