# Generated by Django 2.1.3 on 2019-03-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_auto_20190324_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='meaning1',
            new_name='derivation1_meaning1',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='meaning2',
            new_name='derivation1_meaning2',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='meaning3',
            new_name='derivation1_meaning3',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='meaning4',
            new_name='derivation1_meaning4',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='meaning5',
            new_name='derivation1_meaning5',
        ),
        migrations.AddField(
            model_name='word',
            name='derivation1_symbol',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation2_meaning1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation2_meaning2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation2_meaning3',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation2_meaning4',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation2_meaning5',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation2_symbol',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation3_meaning1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation3_meaning2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation3_meaning3',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation3_meaning4',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation3_meaning5',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation3_symbol',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation4_meaning1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation4_meaning2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation4_meaning3',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation4_meaning4',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation4_meaning5',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation4_symbol',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation5_meaning1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation5_meaning2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation5_meaning3',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation5_meaning4',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation5_meaning5',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation5_symbol',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation6_meaning1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation6_meaning2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation6_meaning3',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation6_meaning4',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation6_meaning5',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation6_symbol',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='word',
            name='symbol',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
