# Generated by Django 2.1.3 on 2019-03-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_auto_20190324_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='derivation_meaning1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation_meaning10',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation_meaning11',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation_meaning12',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation_meaning13',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation_meaning14',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation_meaning15',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation_meaning16',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation_meaning17',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation_meaning18',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation_meaning19',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation_meaning2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation_meaning20',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation_meaning21',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation_meaning22',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation_meaning23',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation_meaning24',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation_meaning25',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation_meaning3',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation_meaning4',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation_meaning5',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation_meaning6',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation_meaning7',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation_meaning8',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='derivation_meaning9',
            field=models.CharField(default='', max_length=20),
        ),
    ]
