# Generated by Django 2.1.3 on 2019-03-24 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0011_auto_20190324_1459'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Word',
            new_name='Root',
        ),
        migrations.RenameField(
            model_name='root',
            old_name='derivation2_meaning10',
            new_name='derivation2_meaning1',
        ),
        migrations.RenameField(
            model_name='root',
            old_name='derivation2_meaning6',
            new_name='derivation2_meaning2',
        ),
        migrations.RenameField(
            model_name='root',
            old_name='derivation2_meaning7',
            new_name='derivation2_meaning3',
        ),
        migrations.RenameField(
            model_name='root',
            old_name='derivation2_meaning8',
            new_name='derivation2_meaning4',
        ),
        migrations.RenameField(
            model_name='root',
            old_name='derivation2_meaning9',
            new_name='derivation2_meaning5',
        ),
        migrations.RenameField(
            model_name='root',
            old_name='derivation3_meaning11',
            new_name='derivation3_meaning1',
        ),
        migrations.RenameField(
            model_name='root',
            old_name='derivation3_meaning12',
            new_name='derivation3_meaning2',
        ),
        migrations.RenameField(
            model_name='root',
            old_name='derivation3_meaning13',
            new_name='derivation3_meaning3',
        ),
        migrations.RenameField(
            model_name='root',
            old_name='derivation3_meaning14',
            new_name='derivation3_meaning4',
        ),
        migrations.RenameField(
            model_name='root',
            old_name='derivation3_meaning15',
            new_name='derivation3_meaning5',
        ),
        migrations.RenameField(
            model_name='root',
            old_name='derivation4_meaning16',
            new_name='derivation4_meaning1',
        ),
        migrations.RenameField(
            model_name='root',
            old_name='derivation4_meaning17',
            new_name='derivation4_meaning2',
        ),
        migrations.RenameField(
            model_name='root',
            old_name='derivation4_meaning18',
            new_name='derivation4_meaning3',
        ),
        migrations.RenameField(
            model_name='root',
            old_name='derivation4_meaning19',
            new_name='derivation4_meaning4',
        ),
        migrations.RenameField(
            model_name='root',
            old_name='derivation4_meaning20',
            new_name='derivation4_meaning5',
        ),
        migrations.RenameField(
            model_name='root',
            old_name='derivation5_meaning21',
            new_name='derivation5_meaning1',
        ),
        migrations.RenameField(
            model_name='root',
            old_name='derivation5_meaning22',
            new_name='derivation5_meaning2',
        ),
        migrations.RenameField(
            model_name='root',
            old_name='derivation5_meaning23',
            new_name='derivation5_meaning3',
        ),
        migrations.RenameField(
            model_name='root',
            old_name='derivation5_meaning24',
            new_name='derivation5_meaning4',
        ),
        migrations.RenameField(
            model_name='root',
            old_name='derivation5_meaning25',
            new_name='derivation5_meaning5',
        ),
    ]
