# Generated by Django 2.1.3 on 2019-03-30 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0016_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
