# Generated by Django 2.1.3 on 2019-03-30 11:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0017_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(default='', max_length=20)),
                ('test_list', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
